<?php 
// Generated by Subsite::writeHostMap() on 27/Jun/13
$subsiteHostmap = array (
  'caaibi.unah.dev' => 'caaibi.unah.dev',
  'dipp.unah.edu.hn' => 'dipp.unah.edu.hn',
  'registro.unah.dev' => 'dipp.unah.edu.hn',
  'admisiones.unah.edu.hn' => 'admisiones.unah.dev',
  'cms.unah.edu.hn' => 'admisiones.unah.dev',
  'admisiones.unah.dev' => 'admisiones.unah.dev',
  'degt.unah.edu.hn' => 'degt.unah.edu.hn',
  'fcm.unah.dev' => 'fcm.unah.dev',
);